### ISSUE TITLE
Oscillation

### ISSUE THREAD

**Issue by twestley** [LightSys/DistKeySim#7]
From README: "The current algorithm, as mentioned before, is prone to oscillations."

**Comment by twestley** [comment]
I'm not seeing what I thought would be evidence of oscillation, i.e., linear or geometric increase in the number of keyspaces as simulation length increases.

See the attached Excel file. Each row show represents the results of one run using the following config.json:

```
{
  "connectionMode": "full",
  "creationRate": 1,
  "csvOutputPath": "outputs/",
  "networkScale": 0.3,
  "numNodes": 10,
  "simLength": 50
}
```

For each run, I modified this config file with the values of connectionMode, simLength, and numNodes shown in the Excel file. Notice that the maximum number of key spaces is dependent on the number of channels, not the simulation length.

Therefore, I suggest there is no oscillation problem.
 
[FindOscillation.xlsx](https://github.com/LightSys/DistKeySim/files/6956359/FindOscillation.xlsx)
[Zip of config inputs and logOutput and logstats outputs](https://1drv.ms/u/s!AmEGbu1_aJ-t8bdP0HyJm6l181_jdw?e=YBS3Y3)

**Comment by sheesania** [comment]
Terry, your conclusion that there isn't currently an oscillation problem looks reasonable to me. I'm not nearly so familiar with the project at this point as you are, though, so you could run this past some of the past contributors if you think that would be helpful. Otherwise, feel free to go on trying out scenarios from the scenarios document and making sure they behave as desired: https://raw.githubusercontent.com/LightSys/DistKeySim/master/ADAK%20Scenarios%201.pdf
